title: "Jorge Fernández Tejedor - Científico de Datos"
description: "Portafolio y CV de Jorge Fernández, científico de datos y analista."
theme: jekyll-theme-cayman
plugins:
  - jekyll-remote-theme
baseurl: "/joferte84.github.io"
